name = "Citizens Initiative"
license = "MIT"
licenselink = "https://github.com/pacollins/calligraphy/blob/master/LICENSE"
description = "A Hugo theme for citizen initiatives and advocacy, forked from Calligraphy."
homepage = "https://github.com/pacollins/calligraphy"
tags = [
  "blog",
  "dark",
  "light",
  "minimal",
  "responsive",
  "personal",
  "portfolio",
  "news"
]
min_version = "0.145.0 extended"

[author]
  name = "Patrick Collins"
  homepage = "https://pacollins.com/"
