blank_issues_enabled = false

[[contact_links]]
    name = "Discussion Board"
    url = "https://github.com/dfrkp/citizens-initiative/discussions"
    about = "Please use the Discussions section to ask for assistance, do not open an issue for questions."
