baseURL = "https://hugo-calligraphy.netlify.app/"
title = "Citizens Initiative"
copyright = "Copyright Â© 2021"
[pagination]
  pagerSize = 6
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
enableEmoji = true

[params]
  cdn = false

[params.brand]
  logo = ""
  name = ""
  logoShort = ""
  nameShort = "Citizens Initiative"
  tagline = "For the People"

[params.meta]
  baseOGImage = "img/screenshot.jpg"
  faviconComplete = true
  faviconSVG = true
  faviconVersion = ""
  faviconMSColor = "#00aba9"
  faviconiOSColor = "#00aba9"

[params.style]
    ## Width ##
    width_site = ""
    width_content = ""
    width-content-min = ""

    ## Type ##
    font_header = "'Zain', sans-serif"
    font_body = "'Zain', sans-serif"

    ## Transitions ##
    transition_base = "0.3s ease-in-out"

    ## Borders ##
    border_radius-small = "5px"
    border_radius-large = "10px"

    ## Global Colors ##
    color_secondary = "#1e3a5f"
    color_button = "#97cc00"
    color_text_light = "#f1fcf4"
    color_text_dark = "#1e3a5f"

    ## Light Mode Colors ##
    color_primary = "#97cc00"
    color_primary_tint = "#d4f0a0"
    color_primary_shade = "#5a7a00"
    color_canvas = "#f8faf5"
    color_canvas_tint = "#ffffff"
    color_canvas_shade = "#1e3a5f"
    color_text = "#1e3a5f"
    color_text_muted = "#4a6a8f"
    color_text_inverted = "#f1fcf4"
    color_text_link = "#7ab000"
    color_ui_float = "#e8f0e0"
    border_color = "#1e3a5f"
    image_filter = "none"

    ## Dark Mode Colors ##
    dark_color_primary = "#97cc00"
    dark_color_canvas = "#1e3a5f"
    dark_color_canvas-tint = "#2a4a6f"
    dark_color_canvas_shade = "#0f1f30"
    dark_color_text = "#f1fcf4"
    dark_color_text_muted = "#b0d0c0"
    dark_color_text_inverted = "#1e3a5f"
    dark_color_text_link = "#b0e040"
    dark_color_ui_float = "#2a4a6f"
    dark_border_color = "#f1fcf4"
    dark_image_filter = "none"

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 20

[[menu.main]]
  identifier = "series"
  name = "Series"
  url = "/series/"
  weight = 40

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 50

################################################################################
######       The block below has additional configuration settings.        #####
######         Users can edit, but for most it won't be necessary.         #####
################################################################################

[outputs]
  home = ["html", "rss"]

[taxonomies]
  author = "authors"
  series = "series"

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.parser.attribute]
  block = true

[markup.goldmark.extensions]
    strikethrough = true

[markup.goldmark.extensions.extras.delete]
    enable = true
          
[markup.goldmark.extensions.extras.insert]
    enable = true

[markup.goldmark.extensions.extras.mark]
    enable = true

[markup.goldmark.extensions.extras.subscript]
    enable = true

[markup.goldmark.extensions.extras.superscript]
    enable = true

[module.hugoVersion]
  extended = true
  min = "0.111.3"

[privacy.x]
  enableDNT = true

[privacy.vimeo]
  enableDNT = true

[privacy.youtube]
  privacyEnhanced = true